config/routes.rb
Rails.application.routes.draw do
  get 'courses/index'
  root 'courses#index'

  get 'greeter/hello'
  get 'greeter/test' => 'greeter#hello'
  get 'greeter/goodbye'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/greeter_controller.rb
class GreeterController < ApplicationController
  def hello
      random_names = ["M","Bond","Penny"]
      @name = random_names.sample
      @time = Time.now
      @times_displayed ||= 0
      @times_displayed += 1
  end
  def goodbye
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greeter_helper.rb
module GreeterHelper
  def formatted_time(time)
    # time string in AM/PM format
    time.strftime("%I:%M%p")
  end
end

app/views/greeter/hello.html.erb
<!-- <% random_names = ["Vitor","Mari","Artur"] %> -->
<!-- <h1>Greetings, <%= random_names.sample %></h1> -->
<h1>Greetings, <%= @name %></h1>
<!-- <p>The time now is <%= Time.now %></p> -->
<p>The time now is <%= formatted_time(@time) %></p>
<p>This page has been viewed <%= @times_displayed %> time(s)</p>

<p><%= link_to "Google", "http://www.google.com" %></p>
<p><%= link_to "Goodbye", greeter_goodbye_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyFirstApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>